package main

import (
	"context"
	"encoding/json"
	"errors"
	"flag"
	"fmt"
	"io"
	"os"
	"os/signal"
	"path/filepath"
	"strings"
	"syscall"
	"time"

	"github.com/royal007a/01agent/internal/engine"
	"github.com/royal007a/01agent/internal/provider"
	"github.com/royal007a/01agent/internal/schema"
	"github.com/royal007a/01agent/internal/tools"
)

var version = "dev"

type cliConfig struct {
	provider        string
	apiKey          string
	baseURL         string
	model           string
	workDir         string
	thinking        bool
	showThinking    bool
	jsonOutput      bool
	showVersion     bool
	maxTurns        int
	maxOutputTokens int64
	tokenBudget     int64
	maxRepeatedCall int
	maxParallel     int
	timeout         time.Duration
	toolTimeout     time.Duration
}

func main() {
	os.Exit(run(os.Args[1:], os.Stdout, os.Stderr))
}

func run(arguments []string, stdout, stderr io.Writer) int {
	config, prompt, err := parseFlags(arguments, stderr)
	if err != nil {
		if errors.Is(err, flag.ErrHelp) {
			return 0
		}
		fmt.Fprintf(stderr, "01agent: %v\n", err)
		return 2
	}
	if config.showVersion {
		fmt.Fprintln(stdout, version)
		return 0
	}

	model, err := buildProvider(config)
	if err != nil {
		fmt.Fprintf(stderr, "01agent: %v\n", err)
		return 2
	}
	readFile, err := tools.NewReadFileTool(config.workDir)
	if err != nil {
		fmt.Fprintf(stderr, "01agent: initialize read_file: %v\n", err)
		return 2
	}
	registry := tools.NewRegistry(
		tools.WithMaxParallel(config.maxParallel),
		tools.WithToolTimeout(config.toolTimeout),
	)
	if err := registry.Register(readFile); err != nil {
		fmt.Fprintf(stderr, "01agent: register read_file: %v\n", err)
		return 2
	}

	handler := eventPrinter(stderr, config.showThinking, config.jsonOutput)
	agent, err := engine.New(model, registry, engine.Config{
		WorkDir:         config.workDir,
		EnableThinking:  config.thinking,
		MaxTurns:        config.maxTurns,
		MaxTokens:       config.tokenBudget,
		MaxRepeatedCall: config.maxRepeatedCall,
		Timeout:         config.timeout,
		OnEvent:         handler,
	})
	if err != nil {
		fmt.Fprintf(stderr, "01agent: initialize engine: %v\n", err)
		return 2
	}

	ctx, stop := signal.NotifyContext(context.Background(), os.Interrupt, syscall.SIGTERM)
	defer stop()
	result, runErr := agent.Run(ctx, prompt)
	if config.jsonOutput {
		if err := json.NewEncoder(stdout).Encode(result); err != nil {
			fmt.Fprintf(stderr, "01agent: encode result: %v\n", err)
			return 1
		}
	} else if result.FinalMessage.Content != "" {
		fmt.Fprintln(stdout, result.FinalMessage.Content)
	} else {
		fmt.Fprintf(stderr, "01agent stopped: %s (turns=%d, tokens=%d)\n", result.Reason, result.Turns, result.Usage.TotalTokens())
	}
	if runErr != nil {
		fmt.Fprintf(stderr, "01agent: %v\n", runErr)
		return 1
	}
	if result.Reason != schema.TerminalCompleted {
		return 1
	}
	return 0
}

func parseFlags(arguments []string, stderr io.Writer) (cliConfig, string, error) {
	config := cliConfig{}
	flags := flag.NewFlagSet("01agent", flag.ContinueOnError)
	flags.SetOutput(stderr)
	flags.StringVar(&config.provider, "provider", envOr("AGENT_PROVIDER", "openai"), "provider protocol: openai or claude")
	flags.StringVar(&config.apiKey, "api-key", os.Getenv("AGENT_API_KEY"), "API key (prefer AGENT_API_KEY)")
	flags.StringVar(&config.baseURL, "base-url", os.Getenv("AGENT_BASE_URL"), "optional compatible API base URL")
	flags.StringVar(&config.model, "model", os.Getenv("AGENT_MODEL"), "model identifier (required)")
	flags.StringVar(&config.workDir, "workdir", ".", "workspace boundary")
	flags.BoolVar(&config.thinking, "thinking", false, "run a tool-free planning call before each action call")
	flags.BoolVar(&config.showThinking, "show-thinking", false, "print Thinking phase text to stderr")
	flags.BoolVar(&config.jsonOutput, "json", false, "write the complete structured result as JSON")
	flags.BoolVar(&config.showVersion, "version", false, "print version and exit")
	flags.IntVar(&config.maxTurns, "max-turns", 32, "maximum model/action turns")
	flags.Int64Var(&config.maxOutputTokens, "max-output-tokens", 4096, "maximum tokens generated by one provider request")
	flags.Int64Var(&config.tokenBudget, "token-budget", 0, "total reported token budget; 0 disables the budget")
	flags.IntVar(&config.maxRepeatedCall, "max-repeated-call", 3, "maximum equivalent tool calls before doom-loop termination")
	flags.IntVar(&config.maxParallel, "max-parallel", 4, "maximum concurrent read-only tool calls")
	flags.DurationVar(&config.timeout, "timeout", 10*time.Minute, "overall run timeout")
	flags.DurationVar(&config.toolTimeout, "tool-timeout", 30*time.Second, "timeout for one tool call")
	flags.Usage = func() {
		fmt.Fprintf(stderr, "Usage: 01agent [flags] <prompt>\n\n")
		flags.PrintDefaults()
	}
	if err := flags.Parse(arguments); err != nil {
		return config, "", err
	}
	if config.showVersion {
		return config, "", nil
	}
	if config.maxTurns <= 0 || config.maxRepeatedCall <= 0 || config.maxParallel <= 0 {
		return config, "", errors.New("max-turns, max-repeated-call, and max-parallel must be positive")
	}
	if config.maxOutputTokens <= 0 {
		return config, "", errors.New("max-output-tokens must be positive")
	}
	if config.tokenBudget < 0 {
		return config, "", errors.New("token-budget must be non-negative")
	}
	if config.timeout <= 0 || config.toolTimeout <= 0 {
		return config, "", errors.New("timeout and tool-timeout must be positive")
	}
	prompt := strings.TrimSpace(strings.Join(flags.Args(), " "))
	if prompt == "" {
		return config, "", errors.New("prompt is required")
	}
	absolute, err := filepath.Abs(config.workDir)
	if err != nil {
		return config, "", fmt.Errorf("resolve workdir: %w", err)
	}
	config.workDir = absolute
	return config, prompt, nil
}

func buildProvider(config cliConfig) (provider.LLMProvider, error) {
	key := strings.TrimSpace(config.apiKey)
	switch strings.ToLower(strings.TrimSpace(config.provider)) {
	case "openai":
		if key == "" {
			key = os.Getenv("OPENAI_API_KEY")
		}
		return provider.NewOpenAI(provider.Config{APIKey: key, BaseURL: config.baseURL, Model: config.model, MaxTokens: config.maxOutputTokens})
	case "claude", "anthropic":
		if key == "" {
			key = os.Getenv("ANTHROPIC_API_KEY")
		}
		return provider.NewClaude(provider.Config{APIKey: key, BaseURL: config.baseURL, Model: config.model, MaxTokens: config.maxOutputTokens})
	default:
		return nil, fmt.Errorf("unsupported provider %q (want openai or claude)", config.provider)
	}
}

func eventPrinter(output io.Writer, showThinking, quiet bool) func(engine.Event) {
	if quiet {
		return nil
	}
	return func(event engine.Event) {
		switch event.Type {
		case engine.EventTurnStarted:
			fmt.Fprintf(output, "[turn %d]\n", event.Turn)
		case engine.EventThinking:
			if showThinking {
				fmt.Fprintf(output, "[thinking] %s\n", event.Message.Content)
			}
		case engine.EventAssistant:
			if event.Message.Content != "" && len(event.Message.ToolCalls) > 0 {
				fmt.Fprintf(output, "[assistant] %s\n", event.Message.Content)
			}
		case engine.EventToolStarted:
			fmt.Fprintf(output, "[tool] %s %s\n", event.ToolCall.Name, string(event.ToolCall.Arguments))
		case engine.EventToolResult:
			status := "ok"
			if event.ToolResult.IsError {
				status = event.ToolResult.ErrorCode
			}
			fmt.Fprintf(output, "[tool:%s] %s (%d bytes)\n", status, event.ToolResult.ToolCallID, len(event.ToolResult.Output))
		}
	}
}

func envOr(name, fallback string) string {
	if value := strings.TrimSpace(os.Getenv(name)); value != "" {
		return value
	}
	return fallback
}
